steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/amazingapp:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/amazingapp:latest']


    args:
    - 'run'
    - 'deploy'
    - 'amazingapp'
    - '--image'
    - 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA'
    - '--region'
    - 'us-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images:
  - gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA

logsBucket: "gs://app-eng"  
